### ISSUE TITLE
Issue with migrating

### ISSUE THREAD

**Issue by mpochron** [QuickRelease/django-tenants-celery-beat#11]
There is the problem with migrating this package ' django_tenants_celery_beat' causes that dependcies are different than after reupdating/reinstalling pip packages from Docker.

```
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration django_tenants_celery_beat.0001_initial is applied before its dependency tenants.0003_auto_20210421_0627 on database 'default'.
```

A temporary solution is to copy the entire package so that the migrations remain unchanged.

**Comment by dave-v** [comment]
Could you provide some more information on your setup? How did you create your migrations?
This package comes with no migrations, so you have to make them yourself.

**Comment by dave-v** [comment]
This should be resolved in 0.2.0.

**Comment by danchorena** [comment]
Hello, I have the 0.1.1 and I am having this problem when I try to makemigrations. It references a tenant migration that is not there. I have uninstalled and reinstalled, I tried to re create the migrations and everything, but nothing works.

Please help

**Comment by danchorena** [comment]
Hello, I have a problem with this migrations. I had to get in the app folder inside the virtualenv, edit the created migration to remove the dependency, run the migrate and everything is fine. But when I run make migrations it re-creates a very similar migration that perform the operations it already did. Am I making any sense? What should I post to make this problem more understandable?
